import { useEffect } from 'react'
import { motion } from 'framer-motion'
import BrushButton from '../components/BrushButton'
import SectionHeading from '../components/SectionHeading'

const tours = [
  ['01','Self-Drive Buggy Tours','/tour-yellow.png','Take the wheel across Dubai’s red dunes while a safety-trained guide leads the route.','Choose a 1-, 2-, or 4-seater buggy for an off-road drive matched to your experience level.'],
  ['02','Group Buggy Tours','/grp.png','High-energy Dubai desert adventures for friends, celebrations, and corporate groups.','Flexible fleet options and guided routes keep groups together while everyone enjoys the dunes safely.'],
  ['03','Family & Kids Buggy Rides','/buggy-duo.jpg','Guided family adventures created around comfort, shared excitement, and desert scenery.','Multi-seat buggies, passenger harnesses, and professional support help families ride confidently.'],
  ['04','Couples Buggy Tours','/image-copy-6.png','Private desert time for two with dune driving and warm sunset views.','Ideal for anniversaries, celebrations, or an adventurous escape from Dubai.'],
  ['05','Night Buggy Tours','/red-buggy.jpeg','Explore the Arabian Desert beneath moonlight, stars, and the glow of buggy headlights.','Cooler air, guided night routes, and stargazing stops create a completely different atmosphere.'],
  ['06','Custom Buggy Packages','/1-hour.jpg','Flexible experiences for events, proposals, photoshoots, and private groups.','Share your occasion, preferred pace, and requirements—we will shape the route around your plans.'],
  ['07','Red Dunes Buggy Ride','/tour-red.png','Take on the steep ridges and striking terrain of Dubai’s legendary red dunes.','High-performance machines and guided routes balance adrenaline, control, and panoramic views.'],
  ['08','Private Buggy Tours','/polaris-buggy.jpg','An exclusive Dubai desert experience with dedicated support and no shared group.','Private buggies, tailored pacing, and optional transport create a seamless premium journey.'],
]

const stats = [['15+','Years of experience'],['UAE','Licensed operator'],['1000cc','Performance fleet'],['0%','Advance payment']]

export default function AboutPage(){
  useEffect(() => {
    const previousTitle = document.title
    const description = document.querySelector('meta[name="description"]')
    const previousDescription = description?.getAttribute('content')
    document.title = 'About Speed Desert Adventure | Dubai Dune Buggy Tours'
    description?.setAttribute('content', 'Meet Speed Desert Adventure, a UAE-licensed Dubai dune buggy tour operator offering guided self-drive, family, group, private, and custom Red Dunes adventures.')
    return () => {
      document.title = previousTitle
      if (previousDescription) description?.setAttribute('content', previousDescription)
    }
  }, [])

  return <main className="about-page">
  <section className="about-hero"><div className="about-hero-photo"/><div className="about-hero-grid"/><motion.div className="about-hero-copy" initial={{opacity:0,x:-50}} animate={{opacity:1,x:0}} transition={{duration:.9,ease:[.22,1,.36,1]}}><span>ABOUT SPEED DESERT ADVENTURE</span><h1>Built for the<br/><em>Dubai dunes.</em></h1><p>Licensed desert expertise. Powerful machines. Unforgettable off-road journeys across the UAE.</p><BrushButton href="#welcome">Discover our story</BrushButton></motion.div></section>

  <section className="welcome-section" id="welcome"><div className="welcome-title"><SectionHeading eyebrow="WELCOME TO THE DESERT" title="Welcome To" accent="Speed Desert Adventure" /></div><div className="welcome-copy"><p className="lead">Speed Desert Adventure is a distinguished UAE desert adventure operator delivering premium dune buggy rides, quad bike experiences, and complete desert safari journeys.</p><p>Our heritage is built on years of creating memorable Dubai adventures with integrity, trusted guest care, and a constant focus on customer satisfaction. From the first enquiry to the final drive across the dunes, our team combines excitement with professional support.</p><h2>Creating memorable Dubai adventures</h2><p>Safety is central to every tour. We plan each desert journey carefully, maintain our vehicles to demanding standards, and provide clear guidance before guests enter the dunes. Competitive packages deliver value without compromising the quality, equipment, or service behind every ride.</p></div><motion.div className="welcome-visual" initial={{opacity:0,x:55}} whileInView={{opacity:1,x:0}} viewport={{once:true,amount:.3}} transition={{duration:.8}}><img src="/guide-teal.png" alt="Speed Desert Adventure buggy overlooking Dubai dunes"/><span>AL BADAYER / UAE</span></motion.div></section>

  <section className="operator-section"><div className="operator-photo"><img src="/about-operator.jpeg" alt="Speed Desert Adventure dune buggy operator in Dubai" loading="lazy"/><div>15+ YEARS<br/><b>DESERT EXPERIENCE</b></div></div><div className="operator-copy"><SectionHeading eyebrow="ABOUT THE OPERATOR" title="Dune Buggy Bashing" accent="Services in Dubai" /><p>Speed Desert Adventure operates high-energy dune buggy tours across Al Badayer’s famous Big Red Desert. With more than 15 years of experience and full UAE licensing, we deliver safe, guided off-road adventures for new riders and experienced thrill-seekers.</p><p>Our fleet includes powerful 1000cc ATVs, Polaris RZR models, and Can-Am Maverick buggies engineered for steep dunes, soft sand, and fast ridge lines. Choose 1-, 2-, or 4-seater options for solo riders, couples, families, and groups.</p><p>Booking is straightforward, with optional pick-up and drop-off across Dubai. Every tour includes a safety briefing, professional guide support, and guided navigation through spectacular red-dune terrain.</p><a href="/#tour-highlights">Explore Dubai buggy packages <i>→</i></a></div></section>

  <section className="choose-section"><SectionHeading eyebrow="EXPERIENCE / SAFETY / VALUE" title="Why Choose Us For" accent="Dubai Buggy Tours?" /><div className="reason-stats">{stats.map(([big,label],i)=><motion.div key={label} initial={{opacity:0,y:25}} whileInView={{opacity:1,y:0}} viewport={{once:true}} transition={{delay:i*.1}}><strong>{big}</strong><span>{label}</span></motion.div>)}</div><div className="choose-columns"><div><h3>Performance without compromise</h3><p>Can-Am Maverick, Polaris RZR, and other high-performance buggies deliver comfort, control, and desert capability. Guides provide a full briefing and prepare helmets, goggles, harnesses, and vehicle protection.</p></div><div><h3>Private desert access</h3><p>Ride across private desert land for a focused, uncrowded experience. Select a self-drive or guided route and choose a pace suited to solo travellers, couples, families, or groups.</p></div><div><h3>More than a buggy ride</h3><p>Available experiences can include sandboarding, camel rides, photo stops, and convenient transport. Reserve without advance payment and pay on arrival.</p></div></div></section>

  <section className="trusted-section"><div className="trusted-copy"><SectionHeading eyebrow="WHY WE ARE TRUSTED" title="UAE Licensed &" accent="Fully Customizable" /><p>Speed Desert Adventure is a UAE-licensed and registered desert adventure company, with professional training, vehicle inspections, guide certification, and guest care aligned with Dubai tourism requirements.</p><p>Our packages can be adapted for family drives, adrenaline rides, sunset tours, and group adventures. We also create bespoke experiences for birthdays, private events, proposals, corporate retreats, photoshoots, and content production.</p></div><div className="trusted-diagram"><div className="trusted-ring"><span>LICENSED</span><span>INSPECTED</span><span>GUIDED</span><span>CUSTOM</span><img src="/includes-orange.png" alt="Top-down Speed Desert Adventure buggy" loading="lazy"/></div></div></section>

  <section className="tour-types-section"><SectionHeading eyebrow="ONE DESERT / MANY WAYS TO RIDE" title="Different Types of" accent="Dune Buggy Tours Dubai" /><p className="tour-types-intro">Explore flexible Dubai dune buggy tours for individuals, couples, families, groups, and private events. Seating options include 1-, 2-, and 4-seater buggies.</p><div className="tour-types-grid">{tours.map(([num,title,image,summary,detail],i)=><motion.article className="tour-type" key={title} initial={{opacity:0,y:35}} whileInView={{opacity:1,y:0}} viewport={{once:true,amount:.2}} transition={{delay:(i%2)*.1,duration:.65}}><div className="tour-type-image"><img src={image} alt={`${title} in Dubai`} loading="lazy"/></div><div className="tour-type-copy"><small>1 / 2 / 4 SEATER OPTIONS</small><h2>{title}</h2><p className="tour-summary">{summary}</p><p>{detail}</p><a href="/#tour-highlights">View tour options <i>↗</i></a></div></motion.article>)}</div></section>

  <section className="about-cta" id="contact"><div className="about-cta-photo"/><motion.div initial={{opacity:0,y:35}} whileInView={{opacity:1,y:0}} viewport={{once:true,amount:.4}}><span>YOUR DESERT STORY STARTS HERE</span><h2>Ready to drive<br/><em>the red dunes?</em></h2><p>Choose your buggy, select your preferred Dubai desert experience, and reserve without advance payment.</p><div><BrushButton>Book your ride</BrushButton><a href="/#tour-highlights">View packages →</a></div></motion.div></section>
</main>}
